---
# This is a sample database file for the CouchRest ORM
:development: &defaults
  :database: themashery_development
  :host: localhost:5984
  :create_db_if_absent: true

:test:
  <<: *defaults
  :database: themashery_test

:production:
  <<: *defaults
  :database: themashery